AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ssu-it-locker

  SSU IT Collage locker reservation system.

Parameters:
  TableName:
    Type: String
    Description: DynamoDB Table name for user, locker information.
    Default: 'LockerTable'
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: !Ref TableName
Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs14.x
    Properties:
      LayerName: "dependencies"
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x
  # Backend Lambda Resources
  CallbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./dist
      Handler: auth.callbackHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        SsuLogin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/auth/callback
            Method: get
  LogoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./dist
      Handler: auth.logoutHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        Logout:
          Type: Api
          Properties:
            Path: /api/auth/logout
            Method: get
  GetLockerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./dist
      Handler: locker.getLockerHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        GetLocker:
          Type: Api
          Properties:
            Path: /api/locker/get
            Method: get
  GetClaimedLockersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./dist
      Handler: locker.getClaimedLockersHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        GetAllLockers:
          Type: Api
          Properties:
            Path: /api/locker/all
            Method: get
  ClaimLockerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./dist
      Handler: locker.claimLockerHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        ClaimLocker:
          Type: Api
          Properties:
            Path: /api/locker/claim
            Method: post
  DynamoDBLockerTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
  FrontS3Bucket:
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store some data'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    Type: 'AWS::S3::Bucket'
  FrontS3BucketPolicy:
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data'
    Properties:
      Bucket: !Ref FrontS3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal: '*'
            Resource:
              - !Sub 'arn:aws:s3:::${FrontS3Bucket}/*'
    Type: 'AWS::S3::BucketPolicy'
  CfApiCachePolicy:
    Properties:
      CachePolicyConfig:
        Name: 'ApiCachePolicy'
        DefaultTTL: 3600
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: 'all'
          HeadersConfig:
            HeaderBehavior: 'whitelist'
            Headers:
              - 'Authentication'
          QueryStringsConfig:
            QueryStringBehavior: 'all'
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
    Type: 'AWS::CloudFront::CachePolicy'
  CfFrontCachePolicy:
    Properties:
      CachePolicyConfig:
        Name: 'FrontCachePolicy'
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: 'all'
          HeadersConfig:
            HeaderBehavior: 'none'
          QueryStringsConfig:
            QueryStringBehavior: 'all'
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
    Type: 'AWS::CloudFront::CachePolicy'
  CfDistribution:
    Metadata:
      Comment: 'A simple CloudFront distribution with an S3 origin'
    Properties:
      DistributionConfig:
        Comment: 'A simple distribution with an S3 origin'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          CachePolicyId: !Ref CfFrontCachePolicy
          TargetOriginId: !Sub 's3-origin-${FrontS3Bucket}'
          ViewerProtocolPolicy: 'redirect-to-https'
        CacheBehaviors:
          - AllowedMethods:
              - 'HEAD'
              - 'DELETE'
              - 'POST'
              - 'GET'
              - 'OPTIONS'
              - 'PUT'
              - 'PATCH'
            CachedMethods:
              - 'HEAD'
              - 'GET'
            CachePolicyId: !Ref CfApiCachePolicy
            PathPattern: 'api/*'
            TargetOriginId: !Sub 'api-origin-${ServerlessRestApi}'
            ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub '${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
            Id: !Sub 'api-origin-${ServerlessRestApi}'
            OriginPath: '/Prod'
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
          - DomainName: !Sub '${FrontS3Bucket}.s3-website.${AWS::Region}.amazonaws.com'
            Id: !Sub 's3-origin-${FrontS3Bucket}'
            OriginPath: ''
            CustomOriginConfig:
              OriginProtocolPolicy: 'http-only'
        PriceClass: 'PriceClass_All'
    Type: 'AWS::CloudFront::Distribution'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SsuLockerApi:
    Description: "API Gateway endpoint URL for Prod stage for SSU Locker function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  FrontS3BucketName:
    Description: 'Bucket name'
    Value: !Ref FrontS3Bucket
  FrontS3BucketWebsiteURL:
    Description: 'Bucket website url'
    Value: !GetAtt FrontS3Bucket.WebsiteURL
  CfDistributionId:
    Description: 'Id for our cloudfront distribution'
    Value: !Ref CfDistribution
  CfDistributionDomainName:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt CfDistribution.DomainName
